services:
  docs:
    container_name: docs
    build:
      context: .
      dockerfile: ./apps/docs/Dockerfile
    ports:
      - "3004:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - default

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "5001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - default

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:

networks:
  default:
    driver: bridge
    name: localhost
