backend:
  name: github
  repo: rodrigo-work/indica-saude
  branch: develop # Branch to update (optional; defaults to master)
  # auth_endpoint: api/auth/ # Essa rota vai ser muito importante mais para frente

# local_backend: false

publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo

media_folder: public/images
public_folder: images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
